{{- if .Values.sentry1.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: sentry1-execution
  namespace: {{ .Values.global.namespace.validators }}
  labels:
    {{- include "ethereum-validator.labels" . | nindent 4 }}
    component: sentry1
    client: execution
spec:
  type: {{ .Values.sentry1.service.execution.type }}
  ports:
  - name: jsonrpc
    port: {{ .Values.sentry1.service.execution.port }}
    targetPort: jsonrpc
  - name: engine
    port: 8551
    targetPort: engine
  - name: metrics
    port: 6060
    targetPort: metrics
  selector:
    {{- include "ethereum-validator.selectorLabels" . | nindent 4 }}
    component: sentry1
    client: execution
---
apiVersion: v1
kind: Service
metadata:
  name: sentry1-consensus
  namespace: {{ .Values.global.namespace.validators }}
  labels:
    {{- include "ethereum-validator.labels" . | nindent 4 }}
    component: sentry1
    client: consensus
spec:
  type: {{ .Values.sentry1.service.consensus.type }}
  ports:
  - name: http
    port: {{ .Values.sentry1.service.consensus.port }}
    targetPort: http
  - name: metrics
    port: 5054
    targetPort: metrics
  selector:
    {{- include "ethereum-validator.selectorLabels" . | nindent 4 }}
    component: sentry1
    client: consensus
{{- end }}
