{{- if .Values.rbac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ethereum-validator.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace.validators }}
  labels:
    {{- include "ethereum-validator.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
